# -*- coding: utf8 -*-

"""
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


def fib(upperbound):
    a, b = 1, 2
    while b < upperbound:
        if b % 2 == 0:
            yield b
        a, b = b, a + b

if __name__ == "__main__":
    print sum(fib(4000000))
